#!/bin/bash

if [ $# -eq 0 ]; then
    echo "command requires an argument 0.2 < X <= 1"
else
    if (( $(echo "$1>0.2 && $1<=1" | bc))); then
        DISPLAYS=$( xrandr --prop | grep " connected" | awk '{print $1}' )
        for display in $DISPLAYS
        do
            echo "setting brightnes for display $display"
            xrandr --output $display --brightness $1
        done
    else
        echo "command requires an argument 0.2 < X <= 1"
    fi
fi
